---
version: 2
multicolumn: false
web-width: 833px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/fig1/fig1.svg
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/165354/articles/189458/master/folder/figures/fig1"
    url: "/users/165354/articles/189458/master/file/figures/fig1/fig1.svg"
